FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./
COPY packages/ ./packages/
COPY apps/web/ ./apps/web/

RUN npm install
RUN npm run build --workspace=@cf-hub/web

FROM node:20-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production

COPY --from=builder /app/apps/web/.next ./apps/web/.next
COPY --from=builder /app/apps/web/public ./apps/web/public
COPY package*.json ./
COPY apps/web/package.json ./apps/web/
COPY packages/ ./packages/

RUN npm install --production

EXPOSE 3000

CMD ["npm", "run", "start", "--workspace=@cf-hub/web"]
