FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./
COPY packages/ ./packages/
COPY apps/api/ ./apps/api/

RUN npm install
RUN npm run build --workspace=@cf-hub/database
RUN npm run build --workspace=@cf-hub/api

FROM node:20-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production

COPY package*.json ./
COPY packages/ ./packages/
COPY apps/api/ ./apps/api/

RUN npm install --production

EXPOSE 4000

CMD ["npm", "run", "start", "--workspace=@cf-hub/api"]
